###get all articles
GET http://localhost:4000/api/currentcheckedinusers/ HTTP/1.1

###
GET http://localhost:4000/api/hallo HTTP/1.1

###test
PATCH http://localhost:4000/api/visits/615ae6338fc1163864348cbb HTTP/1.1
# Content-Type: application/json

# {
#   "counter" : "1235"
# }

### update
PATCH http://localhost:4000/api/playground/61264830a1792817b301dabd HTTP/1.1
Content-Type: application/json

{
  "userId": "0d804961-6236-4773-90cb-f3990a7c6222c"
}

### User infos
GET http://localhost:4000/api/users/622afe4c-628d-40c8-9731-56c9af052679 HTTP/1.1


###Create

POST http://localhost:4000/api/playground HTTP/1.1
Content-Type: application/json

{
  "geometry": {
      "coordinates": [
        11.516052709701846,
        48.11061101493707
      ],
      "type": "Point"
    },
    "userCounter": 1,
    "type": "Feature",
    "id": "node/270951761"
}

###get all users
GET http://localhost:4000/api/user HTTP/1.1

###Create user

POST http://localhost:4000/api/user/ HTTP/1.1
Content-Type: application/json

{
  "userId" : "288c00fc-c7be-483d-b3db-d2a50822a0da",
  "checkedInPlayground" : "1588"
}


###DELETE User
DELETE http://localhost:4000/api/user/0d804961-6236-4773-90cb-f3990a7c6c9c HTTP/1.1

###DELETE all polygons
DELETE http://localhost:4000//api/playground HTTP/1.1



###DELETE Playground
DELETE http://localhost:4000/api/playground/612541ea11dfdb5faf1a99ff HTTP/1.1



### User infos
GET http://localhost:4000/api/user/0d804961-6236-4773-90cb-f3990a7c6c9c HTTP/1.1